library(DESeq2)
library(dplyr)
library(gplots)
library(ggplot2)
library(limma)
library(magrittr)
library(purrr)
library(RColorBrewer)
library(readr)
library(reshape2)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(org.Rn.eg.db)
library(stringr)
library(topGO)
library(tximport)
library(rlang)
library(sva)
library(knitr)

sessionInfo()

writeLines("")
source("https://bioconductor.org/biocLite.R")
