library(DESeq2)
library(dplyr)
library(gplots)
library(ggplot2)
library(magrittr)
library(purrr)
library(RColorBrewer)
library(readr)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(org.Rn.eg.db)
library(stringr)
library(topGO)
library(tximport)

sessionInfo()
