library(DESeq2)
library(dplyr)
library(gplots)
library(ggplot2)
library(ggrepel)
library(GO.db)
library(limma)
library(magrittr)
library(purrr)
library(RColorBrewer)
library(ReactomePA)
library(readr)
library(reshape2)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(org.Rn.eg.db)
library(stringr)
library(topGO)
library(tximport)
library(rlang)
library(sva)
library(knitr)
library(patchwork)
library(conflicted)
library(pheatmap)
library(Rsamtools)
library(GenomicAlignments)
library(BiocParallel)
library(zeallot)
library(ComplexHeatmap)

conflict_prefer("desc", "dplyr")
conflict_prefer("setdiff", "dplyr")
conflict_prefer("intersect", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("reduce", "purrr")
conflict_prefer("rowVars", "matrixStats")
conflict_prefer("set_names", "rlang")
conflict_prefer("clusterExport", "parallel")
conflict_prefer("clusterEvalQ", "parallel")
conflict_prefer("parSapply", "parallel")
conflict_prefer("extract", "magrittr")
conflict_prefer("strsplit", "base")
conflict_prefer("cor", "WGCNA")
conflict_prefer("rename", "dplyr")

sessionInfo()

writeLines("")
BiocManager::version()


